### ISSUE TITLE
Best way to write out more beam info

### ISSUE THREAD

**Issue by annajcrawford** [joeatodd/HiDEM#4]
I'm using the HiDEM-develop branch and am looking to write out more bond information, specifically capturing MAXV and (DL-L) for broken bonds. 

Is the best way to append these new variables to the STR files using the "BinarySTROutput" subroutine in io.f90? I'm wondering if it is possible to do that. If not, I could copy that routine and modify it to write new STR files containing MAXV and (DL-L)?

Other ideas?

I figure that I can use our python analysis scripts to gather the data I need from broken bonds afterwards.

**Comment by joeatodd** [comment]
Yeah you can just add variables for MAXV and DL-L as arguments to BinaryStrOutput, and make modifications inside like increasing Nvars, and modifying the loop over NTOT:
```
  !Write our EFS values to work array
  counter = 0
  DO j=1,NTOT
    IF(NANPart(j) < myid) CYCLE
    counter = counter + 1
    work_real(counter) = EFS(j)
  END DO
```
to also write out the other variables.
